### 파이썬 연산 특징

최종 정리

---


Opnecv - Core Operations

https://docs.opencv.org/4.x/d7/d16/tutorial_py_table_of_contents_core.html



In [2]:
a = 3
b = 4

In [5]:
a+b

7

In [3]:
# 위 a+b 는 내부적으로 아래와 같이 연산됨

# method 방식
a.__add__(b)

7

In [6]:
from operator import add

In [7]:
add(a, b)

7

In [8]:
class C:
    pass

In [9]:
c = C()

In [11]:
# 합이 안된다.
c + c

TypeError: unsupported operand type(s) for +: 'C' and 'C'

In [ ]:
# __add__ 가 없다.
dir(c)

In [ ]:
class D:
    def __add__(self, x):    # operator overloading
        return 1
    
d = D()

In [ ]:
d + d

#  연산이 간능해 진다. (오퍼레이터 오버로딩 때문에 가능)

1

In [ ]:
# 최종적으로 
np.add
cv2.add
# 는 다른 add 이다.

In [ ]:
a+b 
a.__add__(b)

# 위 두 개는 기본적으로 같고,

class D 

# 처럼 함수로 만들어서도 연산이 가능하게 하는게 파이썬 연산자의 특싱

---

In [1]:
import numpy as np

In [18]:
np.add(3,4)

# np 는 스칼라가 들어오면 파이썬과 거의 똑같이 연산

7

In [26]:
np.add([1,2,3],[3,4,5])

# 스칼라가 아니면 (array면), 엘리멘트 와이즈 연산을 한다.

array([4, 6, 8])

In [2]:
import cv2

In [21]:
cv2.add(3,4)

# cv2 는 다르게 연산한다.

array([[7.],
       [0.],
       [0.],
       [0.]])

In [23]:
# 연산 못함.
cv2.add([1,2,3],[4,5,6])

# 에러 메세지에
# Overload resolution failed:

error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'add'
> Overload resolution failed:
>  - src1 is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src1'


In [24]:
x = np.array([1,2,3])
y = np.array([3,4,5])

In [25]:
cv2.add(x,y)
# 2차원으로 결과를 냄.
# but, numpy 는 자기에 맞게 결과를 냄

array([[4],
       [6],
       [8]], dtype=int32)

---

### @ 는 np 에서만 사용 가능한 연산자 이다.

https://peps.python.org/

개발자 파이썬 코딩 스타일   
=> 유명한 3118 과 465 에서 @ 연산자 사용을 제시 (PEP456 / PEP3118)  
=> python 에서 ㅇㅋ  

In [4]:
# np 연산은 차원에 맞춰서 해줌
np.bitwise_and(5,4)

4

In [5]:
np.bitwise_and([5,3],[4,3])

array([4, 3], dtype=int32)

In [6]:
# 차원이 안맞아도 알아서 잘 계산해 줌 => boladcasting
np.bitwise_and([5,3],[4])

array([4, 0], dtype=int32)

### 그러나 cv2 는

In [7]:
# 스칼라 형식은 계산이 됨. 하지만 2차원으로 결과를 줌
cv2.bitwise_and(5,4)

array([[4.],
       [0.],
       [0.],
       [0.]])

In [8]:
cv2.bitwise_and([5,3],[4,3])

# 계산이 안되는 이유는 리스트에 대한 자동 broadcasting 이 안되서
# array로 직접 저장해주면 계산 됨

error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'bitwise_and'
> Overload resolution failed:
>  - src1 is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src1'


In [9]:
# array로 직접 지정해주면 계산 됨
cv2.bitwise_and(np.array([5,3]), np.array([4,3]))

array([[4],
       [3]], dtype=int32)