# SET (집합)

In [1]:
a = {1, 2, 1, 1, 3, 2}
a

{1, 2, 3}

In [2]:
a = {1, 2, 3}
b = {2, 3, 4}

In [3]:
# 차집합
a-b

{1}

In [4]:
# 교집합
a & b

{2, 3}

In [5]:
# 합집합
a|b

{1, 2, 3, 4}

In [6]:
# 대칭차집합 (a, b 에서 교집합을 뺀 나머지)
a^b

{1, 4}

In [9]:
# not
c = 5

---

### bit length 연산

In [12]:
c.bit_length()

3

In [13]:
# 비트랭스가 다른 애들끼리 연산
d = 17
e = 3

# 뒤에서부터 맞춤
# 모두 1일 때만 1을 반환

In [14]:
bin(d)

'0b10001'

In [15]:
bin(e)

'0b11'

In [16]:
d & e

"""
10001
   11
00001 이므로 1이됨
"""

1

In [17]:
d = 5
f = 6

In [22]:
# 비트연산자

# or
d|f

7

In [24]:
# not (bitwise not , 비트연산자 not)
~d

"""
2진을 10진으로 바꾸어 생각한다.

~5 를 구한다고 하면

5의 이진 101
6의 이진 110  이지만,

간단히 생각해서 => 5에 부호를 바꿔주고 -1 해준다.
=> -5 -1 => -6

따라서 ~5 의 값은 -6 이다.
"""
# 컴플리맨트 - 부호를 결정

-6

In [ ]:
############# 0508 / 33분 30초

In [10]:
# python은 4가지 진법을 지원한다.
# 2진수 (파이썬은 bin(2진), oct(8진), hex(16진), 10진 => 4가지 지원)
bin(5)

'0b101'

In [11]:
# 2진수를 입력하면 10진으로 돌려줌 (0b 2진)
0b1111

15

In [ ]:
# 연산자 오버로딩
# 데이터 타입마다 다른 기능을 할수 있게 만든 것.

# 메소드 오버로딩
# Java 는 지원하지만, 파이썬은 지원하지 않음
"""
java 에서는 아래 두개를 다른 함수로 인식, but 파이썬은 같은 것으로 인식
def x():
    pass
def x(a):
    pass
"""

In [1]:
import tensorflow as tf

In [8]:
# broadcasting, ufunc (numpy)

tf.square([1,2]) + tf.square(3)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 13])>

In [3]:
import cv2
import numpy as np

In [26]:
# cv => bitwise 연산
cv2.bitwise_and(5,6)

# openev 는 이미지연산을 위해 만들었기 때문에, 2차원, 3차원을 겨냥함.
# 마스크 라는 개념


array([[4.],
       [0.],
       [0.],
       [0.]])

In [28]:
# numpy => bitwise 연산
np.bitwise_and(5,6)

4

In [ ]:
# 같은 bitwise 연산이지만 값이 다르게 나옴.

In [32]:
# np => bitwise 연산
np.bitwise_and([5,5],[6,6])

array([4, 4], dtype=int32)

---

---

---

다시하번 정리

# operator overloading
- (methrod overloading은 아니다)


데이터 타입마다 다른 기능을 할수 있게 만든 것.

In [41]:
from operator import add

In [42]:
add(3,4)
# 는 3+4 와 같다.

7

In [43]:
dir(im)
# '__add__',  가 있으면, add 가 가능

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [33]:
# cv2.add 와 np.add 의 연산 차이

cv2.add(128, 127)

# 결과가 4개로 나옴

array([[255.],
       [  0.],
       [  0.],
       [  0.]])

In [34]:
np.add(128,129)

# 결과가 한개

257

In [35]:
im = cv2.imread('1.jpg')
im.dtype

dtype('uint8')

In [39]:
# 파이썬 opencv는 numpy로 만들었지만, 연산이 다른경우가 많다.

cv2.add(im,im)[0][0:3]
# saturated  연산 (항상 saturated 연산이 아니라 확인해야 한다.)


array([[  4, 255, 255],
       [  4, 255, 255],
       [  4, 255, 255]], dtype=uint8)

In [40]:
np.add(im, im)[0][0:3]
# modular 연산

array([[  4, 166, 254],
       [  4, 166, 254],
       [  4, 166, 254]], dtype=uint8)

---
다시한번 정리

In [ ]:
# opencv 의 기본적인 연산

# numpy 하고 내부적으로는 같이만, 내부적으로 이미지 전용으로 만들 놓은 것이 있다.

# add 에서 numpy 와 opnecv 와 다르게 연산된다.

# numpy 기본적으로 자기 차원에 맞춰서 연산. 대부분 overloading (데이터 구조에 맞춰서 정의)
# 차원에 맞춰 결과를 자동으로 변환

# cv 는 numpy와 Scalar만 overloading 되어있고, 그외 나머지는 2차원으로 결과값을 내준다.
# (Scalar = int(정수), float(실수), None(값없음), bool(True, False) 4가지)

In [ ]:
# 행렬곱에 대한 연산 제외하고,

In [ ]:
# @ 는 유일하게 numpy 에서만 연산자로 사용된다.

# PEP8 : 파이썬 코딩 스타일 - 3118 - 465 : numpy 에서 @ 연산을 제안

In [4]:
# np 연산은 차원에 맞춰서 해줌
np.bitwise_and(5,4)

4

In [5]:
np.bitwise_and([5,3],[4,3])

array([4, 3], dtype=int32)

In [6]:
# 차원이 안맞아도 알아서 잘 계산해 줌 => boladcasting
np.bitwise_and([5,3],[4])

array([4, 0], dtype=int32)

하지만, cv2는

In [7]:
# 스칼라 형식은 계산이 됨. 하지만 2차원으로 결과를 줌
cv2.bitwise_and(5,4)

array([[4.],
       [0.],
       [0.],
       [0.]])

In [9]:
cv2.bitwise_and([5,3],[4,3])

# 계산이 안되는 이유는 리스트에 대한 자동 broadcasting 이 안되서
# array로 직접 저장해주면 계산 됨

error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'bitwise_and'
> Overload resolution failed:
>  - src1 is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src1'


In [10]:
# array로 직접 지정해주면 계산 됨
cv2.bitwise_and(np.array([5,3]), np.array([4,3]))

array([[4],
       [3]], dtype=int32)

In [13]:
#### bitwise not

np.bitwise_not(3)

-4

In [12]:
cv2.bitwise_not(3)

# bit 수에 따져서 다르게 연삼함.
# 2차원 기본임(이미지 전용) = 따라서 np와 다르게 계산하는 경우가 많다.

array([[-1.5],
       [ nan],
       [ nan],
       [ nan]])

---
### 3. mask

cv2 의 bitwise_and 파라미터를 보면 mask 등장

(function) bitwise_and: (src1: Mat, src2: Mat, dts: Mat = ..., mask: Mat = ...) -> Any

https://docs.opencv.org/4.x/d0/d86/tutorial_py_image_arithmetics.html

이미지 (cv 공식 깃)
https://github.com/opencv/opencv/tree/master/samples/data