In [2]:
a = 3
b = 4

In [5]:
a+b

7

In [3]:
# 위 a+b 는 내부적으로 아래와 같이 연산됨

# method 방식
a.__add__(b)

7

In [6]:
from operator import add

In [7]:
add(a, b)

7

In [8]:
class C:
    pass

In [9]:
c = C()

In [11]:
# 합이 안된다.
c + c

TypeError: unsupported operand type(s) for +: 'C' and 'C'

In [ ]:
# __add__ 가 없다.
dir(c)

In [13]:
# 예시
class D:
    def __add__(self, x):  ### operator overlading
        return 1

In [14]:
d = D()

In [15]:
d + d

1

np.add  
cv2.add  

의 값이 데이터 타입에 따라 다를 수 있다.  
왜? = 정의가 다르기 때문에  

opencv 는 numpy 기반으로 만들었지만, 연산이 다르게 된다.

그 예시중 하나가 set

In [17]:
import numpy as np

In [18]:
np.add(3,4)

7

In [26]:
np.add([1,2,3],[3,4,5])

array([4, 6, 8])

In [20]:
import cv2

In [21]:
cv2.add(3,4)

array([[7.],
       [0.],
       [0.],
       [0.]])

In [23]:
# 연산 못함.
cv2.add([1,2,3],[4,5,6])

# Overload resolution failed:

error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'add'
> Overload resolution failed:
>  - src1 is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src1'


In [24]:
x = np.array([1,2,3])
y = np.array([3,4,5])

In [25]:
cv2.add(x,y)
# 2차원으로 결과를 냄.
# numpy 는 자기에 맞게 결과를 냄

array([[4],
       [6],
       [8]], dtype=int32)